// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqPWGdJJ3pc2wgQWbCmK6KrdKxUk3vo7U',
    appId: '1:1044629755773:web:d681e2312f755782975e14',
    messagingSenderId: '1044629755773',
    projectId: 'study-buddy-6443c',
    authDomain: 'study-buddy-6443c.firebaseapp.com',
    storageBucket: 'study-buddy-6443c.appspot.com',
    measurementId: 'G-2JG472FRFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWkD5qcDmOVye3mOZ99g2-bJYChNIYcaE',
    appId: '1:1044629755773:android:af82ca77cc73895f975e14',
    messagingSenderId: '1044629755773',
    projectId: 'study-buddy-6443c',
    storageBucket: 'study-buddy-6443c.appspot.com',
    databaseURL:
        'https://study-buddy-6443c-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkE-orhwUSfMEBvTh1hYWLWBq0-K8Q3kU',
    appId: '1:1044629755773:ios:93330f056ee4bf2b975e14',
    messagingSenderId: '1044629755773',
    projectId: 'study-buddy-6443c',
    storageBucket: 'study-buddy-6443c.appspot.com',
    iosClientId:
        '1044629755773-7njgb18b0rppsbe64ie2l3f0u112p8s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.apktestproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkE-orhwUSfMEBvTh1hYWLWBq0-K8Q3kU',
    appId: '1:1044629755773:ios:93330f056ee4bf2b975e14',
    messagingSenderId: '1044629755773',
    projectId: 'study-buddy-6443c',
    storageBucket: 'study-buddy-6443c.appspot.com',
    iosClientId:
        '1044629755773-7njgb18b0rppsbe64ie2l3f0u112p8s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.apktestproject',
  );
}
